version: '3.9'
services:
  node:
    image: node:18-alpine3.16
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - mongo
      - redis
    command: npm start

  mongo:
    image: "mongo:6.0.6-jammy"
    expose:
      - "27017"
    ports:
      - "27017:27017"

  redis:
    image: "redis:7.0.11-alpine"